language: go
go:
  - 1.12.4
  - tip
matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    recipients: dean.karn@gmail.com
    on_success: change
    on_failure: always

before_install:
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover

before_script:
  - go get -t ./...

script:
  - make test

after_success: |
  [ $TRAVIS_GO_VERSION = 1.11.4 ] &&
  overalls -project="github.com/go-playground/pkg" -covermode=count -ignore=.git,_examples,testdata -debug &&
  goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN